### ISSUE TITLE
"detailed_summary: true" option doesn't provide detailed table

### ISSUE THREAD

**Issue by vitalyk-multinarity** [mikepenz/action-junit-report#645]
I tried to activate a detailed report by using "detailed_summary: true" option, but it didn't work - there is empty table (see attached screenshot).

Thanks, 
Vitaly

![Screen Shot 2022-08-22 at 16 02 50](https://user-images.githubusercontent.com/97117484/185927944-22f72503-c0f7-4a37-b09e-0679f3e0d16c.png)

**Comment by mikepenz** [comment]
@vitalyk-multinarity thank you very much for the report. 

Do you have some additional details on the run, possibly the log output of github actions itself? 
Is this maybe an open source repo where I could have a look in the run directly?


Here's an example run with the output visible: https://github.com/mikepenz/action-junit-report/actions/runs/2894267304#summary-7930673877

**Comment by vitalyk-multinarity** [comment]
@mikepenz - Thank you!
Unfortunately, this is closed-source project. We're using 'ctest --output-junit'.
I'm attaching the log output from the action. I can share XML report if relevant.
[publish.log](https://github.com/mikepenz/action-junit-report/files/9400266/publish.log)

**Comment by mikepenz** [comment]
Thanks for the additional insight. I think the problem is related to the `include_passed` configuration. 

Your testcase above does indicate that there were no failures, and the `include_passed` flag is set to `false` 

Annotations are not extracted for passed tests if it is set to false. See the code here: https://github.com/mikepenz/action-junit-report/blob/e187db4c8bb2e72c0032eefc75c5124e383a48d4/src/testParser.ts#L273

See the configuration here: https://github.com/mikepenz/action-junit-report/blob/e187db4c8bb2e72c0032eefc75c5124e383a48d4/action.yml#L53-L56

And I just realised that this config is missed in the table in the README. Apologies for this.

**Comment by vitalyk-multinarity** [comment]
@mikepenz , Thank you again! "include_passed:true" did it work.
Vitaly
